services:
   - docker
language: csharp
solution: dotnetMPL.sln
mono: none
dotnet: 3.1
script:
 - dotnet restore
 - dotnet test
 - dotnet publish TCPResponderTest/ -c Release
after_success:
 - sh .travis/deploy_dockerhub.sh
